version: '3.5'
services:
    redis_user:
        container_name: redis-serasa
        image: sickp/alpine-redis:3.2.2
        ports:
            - "6379:6379"
        networks:
            - proxynet

    elasticsearch:
        image: elasticsearch:6.5.0
        container_name: laravel-elasticsearch
        ports:
            - "9200:9200"
        networks:
            - proxynet

    kibana:
        image: docker.elastic.co/kibana/kibana:6.3.2
        container_name: kibana
        ports:
            - "5601:5601"
        networks:
            - proxynet

    database:
        image: mariadb:10.3
        container_name: laravel-database
        volumes:
            - ./db:/var/lib/mysql
        environment:
            - "MYSQL_DATABASE=serasa"
            - "MYSQL_USER=admin"
            - "MYSQL_PASSWORD=123"
            - "MYSQL_ROOT_PASSWORD=123"
        ports:
            - "3306:3306"
        networks:
            - proxynet

networks:
    proxynet:
        name: db_network