version: '3.5'
services:
#  redis_user:
#    container_name: redis-order-serasa
#    image: sickp/alpine-redis:3.2.2
#    ports:
#      - "6379:6379"
  app-order:
    build:
      context: ./
      dockerfile: app.dockerfile
    working_dir: /var/www
    container_name: order-php
    volumes:
      - ./:/var/www
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=database"
    networks:
      - db-net
  web-order:
    build:
      context: ./
      dockerfile: web.dockerfile
    working_dir: /var/www
    container_name: order-web
    volumes:
      - app
    ports:
      - 8888:8888
    networks:
      - db-net

networks:
  db-net:
    external:
      name: db_network

#  elasticsearch:
#    image: elasticsearch:6.5.0
#    container_name: order-elasticsearch
#    ports:
#      - "9200:9200"

    # The Database
#  database:
#    image: mariadb:10.3
#    container_name: order-database
#    volumes:
#      - ./db:/var/lib/mysql
#    environment:
#      - "MYSQL_DATABASE=serasa"
#      - "MYSQL_USER=admin"
#      - "MYSQL_PASSWORD=123"
#      - "MYSQL_ROOT_PASSWORD=123"
#    ports:
#      - "3306:3306"
